/* The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 */

class Euler012{
  public static int numDivisors(int x){
    int divisors = 2;
    double sqrtX = Math.sqrt(x);

    for(int i = 2; i <= sqrtX; i++){
      if(x % i == 0){
        divisors+=2;
      }
      if(sqrtX == i){
        divisors--;
      }
    }

    return divisors;
  }

  public static int calc(int numDivisors){
    int triangleNum = 1;
    int divisors = 1;
    int tempDivisors;

    int x = 1;
    while(divisors < numDivisors){
      x++;
      triangleNum += x;
      tempDivisors = numDivisors(triangleNum);
        if(tempDivisors > divisors)
          divisors = tempDivisors;
    }

    return triangleNum;
  }

  public static void main(String arg[]){
    int solution = calc(500);
    System.out.println(solution);
  }
}
