/* Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will
 * be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

class Euler002{
  private static int fibonacci(int x){
    int last = 0;
    int current = 1;
    int temp;
    int total = 0;
    String str;
    for(int i = 0; current < x; i++){
      temp = last;
      last = current;
      current += temp;
      /*
       * str = String.format("%d, %d", last, current);
       * System.out.println(str);
       */
      if(current % 2 == 0){
        total += current;
      }
    }
    return total;
  }

  public static void main(String arg[]){
    System.out.println(fibonacci(4000000));
  }
}
